name: Sync Airflow DAG Prod

on:
  push:
    paths:
      - "airflow/**"
  workflow_dispatch:

jobs:
  ci-cd:
    uses: mindearth/dev-ops/.github/workflows/airflow-dags-sync.yml@main
    secrets: inherit
